"use strict";

document.addEventListener("DOMContentLoaded", () => {
    initializeMobileMenu(); initializeStickyHeader(); initializeScrollReveal(); initializeSmoothScrolling(); initializeFAQ(); initializeCurrentYear(); initializeContactForm(); initializeCounters(); initializeSitewideFooter();
});

function initializeSitewideFooter() {
    const footer = document.querySelector(".site-footer");
    const container = footer?.querySelector(".container");
    if (!container) return;
    container.innerHTML = `<div class="footer-logo"><a href="index.html" class="brand" aria-label="Quantify Data Solutions home"><img src="Images/QDS Logo.png" alt="Quantify Data Solutions logo" class="brand-logo"><div class="brand-name">Quantify <span>DATA SOLUTIONS</span></div></a></div><div class="footer-columns"><div class="footer-column"><h4>COMPANY</h4><a href="index.html">Home</a><a href="about.html">About</a><a href="services.html">Services</a><a href="contact.html">Contact</a></div><div class="footer-column"><h4>SERVICES</h4><a href="services.html#sports-data-details">Sports Data</a><a href="services.html#video-details">Video Annotation</a><a href="services.html#ai-details">AI & ML Data</a><a href="services.html#software-details">Technology</a></div><div class="footer-column"><h4>CONTACT</h4><a href="mailto:info@quantifydatasolutions.in">info@quantifydatasolutions.in</a><span>Nashik, Maharashtra, India</span><a href="contact.html">Start a conversation</a></div></div><div class="footer-bottom"><span>© <span id="currentYear"></span> Quantify Data Solutions. All rights reserved.</span><span>Built for data-driven businesses.</span></div>`;
    let link = document.querySelector('link[data-footer-sitewide="true"]');
    if (!link) { link = document.createElement("link"); link.rel = "stylesheet"; link.dataset.footerSitewide = "true"; document.head.appendChild(link); }
    link.href = "homepage-footer.css?v=20260816-left-sitewide";
}

function initializeMobileMenu() {
    const b=document.getElementById("mobileMenuButton"),n=document.getElementById("mainNavigation"); if(!b||!n)return; const i=b.querySelector("i"),s=o=>{n.classList.toggle("open",o);document.body.classList.toggle("mobile-menu-open",o);b.setAttribute("aria-expanded",String(o));b.setAttribute("aria-label",o?"Close navigation menu":"Open navigation menu");if(i){i.classList.toggle("fa-bars",!o);i.classList.toggle("fa-xmark",o)}};b.addEventListener("click",()=>s(!n.classList.contains("open")));n.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>s(false)));document.addEventListener("click",e=>{if(n.classList.contains("open")&&!n.contains(e.target)&&!b.contains(e.target))s(false)});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&n.classList.contains("open")){s(false);b.focus()}});window.addEventListener("resize",()=>{if(innerWidth>820)s(false)})
}
function initializeStickyHeader(){const h=document.getElementById("siteHeader");if(!h)return;const u=()=>h.classList.toggle("scrolled",scrollY>30);u();addEventListener("scroll",u,{passive:true})}
function initializeScrollReveal(){const e=document.querySelectorAll(".reveal");if(!e.length)return;if(matchMedia("(prefers-reduced-motion: reduce)").matches){e.forEach(x=>x.classList.add("visible"));return}const o=new IntersectionObserver((a,t)=>a.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");t.unobserve(x.target)}}),{threshold:.12,rootMargin:"0px 0px -40px 0px"});e.forEach(x=>o.observe(x))}
function initializeSmoothScrolling(){document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const id=a.getAttribute("href");if(!id||id==="#")return;const t=document.querySelector(id);if(!t)return;e.preventDefault();const h=document.querySelector(".site-header"),hh=h?h.offsetHeight:0;scrollTo({top:t.getBoundingClientRect().top+scrollY-hh-15,behavior:"smooth"})}))}
function initializeFAQ(){const a=document.querySelectorAll(".faq-item");a.forEach(i=>i.addEventListener("toggle",()=>{if(i.open)a.forEach(o=>{if(o!==i)o.open=false})}))}
function initializeCurrentYear(){document.querySelectorAll("#currentYear").forEach(e=>e.textContent=new Date().getFullYear())}
function initializeContactForm(){const f=document.getElementById("contactForm");if(!f)return;f.addEventListener("submit",async e=>{e.preventDefault();const b=f.querySelector('button[type="submit"]'),o=b?b.innerHTML:"";clearFormMessage(f);if(!f.checkValidity()){f.reportValidity();return}if(b){b.disabled=true;b.innerHTML='Sending Inquiry <i class="fa-solid fa-spinner fa-spin"></i>'}try{const r=await fetch("contact-handler.php",{method:"POST",body:new FormData(f),headers:{Accept:"application/json"}});let x={};try{x=await r.json()}catch(_){}if(!r.ok||!x.success)throw Error(x.message||"We could not send your inquiry right now.");showFormMessage(f,"Thank you. Your inquiry has been sent successfully. Our team will get back to you soon.",true);f.reset()}catch(x){showFormMessage(f,x.message||"We could not send your inquiry right now. Please email info@quantifydatasolutions.in directly.",false)}finally{if(b){b.disabled=false;b.innerHTML=o}}})}
function clearFormMessage(f){f.querySelector(".form-success-message")?.remove();f.querySelector(".form-error-message")?.remove()}
function showFormMessage(f,m,s){clearFormMessage(f);const e=document.createElement("div");e.className=s?"form-success-message":"form-error-message";e.setAttribute("role",s?"status":"alert");e.style.cssText=`display:flex;align-items:center;gap:10px;padding:14px 16px;margin-top:4px;border-radius:10px;font-size:.8rem;border:1px solid ${s?"rgba(22,199,154,.25)":"rgba(255,100,100,.3)"};background:${s?"rgba(22,199,154,.07)":"rgba(255,100,100,.07)"};color:#b7c5d3`;e.innerHTML=`<i class="fa-solid ${s?"fa-circle-check":"fa-circle-exclamation"}"></i><span></span>`;e.querySelector("span").textContent=m;f.appendChild(e)}
function initializeCounters(){const c=document.querySelectorAll("[data-counter]");if(!c.length)return;const final=()=>c.forEach(setCounterFinalValue);if(matchMedia("(prefers-reduced-motion: reduce)").matches){final();return}const o=new IntersectionObserver((a,t)=>a.forEach(x=>{if(x.isIntersecting){animateCounter(x.target);t.unobserve(x.target)}}),{threshold:.5});c.forEach(x=>o.observe(x))}
function setCounterFinalValue(c){const t=parseFloat(c.dataset.counter);if(Number.isNaN(t))return;c.textContent=(c.dataset.prefix||"")+t.toLocaleString("en-IN",{minimumFractionDigits:+(c.dataset.decimals||0),maximumFractionDigits:+(c.dataset.decimals||0)})+(c.dataset.suffix||"")}
function animateCounter(c){const t=parseFloat(c.dataset.counter);if(Number.isNaN(t))return;const d=+(c.dataset.duration||1800),p=c.dataset.prefix||"",s=c.dataset.suffix||"",n=+(c.dataset.decimals||0),st=performance.now(),u=now=>{const q=Math.min((now-st)/d,1),v=t*(1-Math.pow(1-q,3));c.textContent=p+v.toLocaleString("en-IN",{minimumFractionDigits:n,maximumFractionDigits:n})+s;if(q<1)requestAnimationFrame(u)};requestAnimationFrame(u)}
